### ISSUE TITLE
Not working on 10.11

### ISSUE THREAD

**Issue by SLboat** [synthesizerpatel/lockscreen#1]
hmmm,i build and run it,but appears not work for hotkey

**Comment by synthesizerpatel** [comment]
Worked for me.. Are you using a generic PC USB keyboard or a Mac keyboard?

**Comment by SLboat** [comment]
hi!nice to meet you,i use the mac wireless keyboard

**Comment by SLboat** [comment]
can i ask,why use the screensaver to lock screen?should we just immediately lock it?

**Comment by synthesizerpatel** [comment]
This program is only designed for use with PC keyboards. 

As far as why use the screen saver to lock the screen.. It's a personal preference.

Best of luck!
